title: Hilary Chang
logo: /pics/SSA2024_PW.jpg
description: Near-surface geophysics/seismology.
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  
# Reading Files
include:
  - _pages
