title: Hilary Chang
logo: /pics/SSA2024_PW.jpg
description: Near-surface geophysics/seismology.
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
# Reading Files
include:
  - _pages
  - _posts
  - _data


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _docs
  - scope:
      path: "doc"
      type: pages
    values:
      layout: single
      author_profile: false
    sidebar:
      nav: "docs"
